# Generated by Django 5.2.4 on 2025-07-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Full name')),
                ('age', models.PositiveBigIntegerField(help_text='Enter age')),
                ('instrument', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'musician',
            },
        ),
    ]
