# Generated by Django 5.2.4 on 2025-07-31 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display_page', '0002_musician'),
    ]

    operations = [
        migrations.CreateModel(
            name='citizenship',
            fields=[
                ('citizenship_number', models.PositiveIntegerField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('issued_date', models.DateField()),
                ('issued_date_my', models.DateField(auto_now_add=True)),
                ('district', models.CharField(choices=[('ktm', 'kathmandu'), ('Bkt', 'Bhaktapur'), ('Llp', 'Lalitpur'), ('Phk', 'Pokhara')], max_length=30)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='display_page.person')),
            ],
        ),
    ]
