# Generated by Django 5.2.4 on 2025-07-31 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display_page', '0004_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='first_name',
            new_name='car_name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='last_name',
        ),
    ]
